#!/bin/bash

  ## 2018.1.25 comparison
  # echo "app = PPR, dataset = soc-LiveJournal1.txt from echo" >> graphchi_metrics.txt.statistics 
  # echo "source=0, nsource=1, walkspersource=100000, nsteps=20 from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/personalizedpagerank1 file '/home/wang/Documents/graph processing system/dataset/LiveJournal1/soc-LiveJournal1.txt' nvertices 4847571 source 0 R 100000 L 20
  # done

  echo "app = PPR, dataset = twitter_rv.net from echo" >> graphchi_metrics.txt.statistics 
  echo "source=12, nsource=1, walkspersource=100000, nsteps=20 from echo" >> graphchi_metrics.txt.statistics 
  for(( times = 0; times < 5; times++))
  do
      echo "times = " $times " from echo"
      bin/example_apps/personalizedpagerank1 file '/home/wang/Documents/graph processing system/dataset/Twitter/twitter_rv.net' nvertices 61578415 source 12 R 100000 L 20
  done

  ## 2018.1.23 comparison
  # echo "app = RWDomination, dataset = soc-LiveJournal1.txt from echo" >> graphchi_metrics.txt.statistics 
  # echo " R = 10, L = 10 from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/rwdomination file '/home/wang/Documents/graph processing system/dataset/LiveJournal1/soc-LiveJournal1.txt' R 10 L 10
  # done

 ## 2018.1.24 comparison
  # echo "app = RWDomination, dataset = twitter_rv.net from echo" >> graphchi_metrics.txt.statistics 
  # echo " R = 10, L = 10 from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/rwdomination file '/home/wang/Documents/graph processing system/dataset/Twitter/twitter_rv.net' R 10 L 10
  # done

# echo "app = AvgDegree, dataset = undirected-LiveJournal1.txt from echo" >> graphchi_metrics.txt.statistics 
#   echo " nsteps=20, tail=0, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#   for(( times = 0; times < 10; times++))
#   do
#       echo "times = " $times " from echo"
#       bin/example_apps/avgdegree file '/home/wang/Documents/graph processing system/dataset/LiveJournal_undirected/LiveJournal1.txt' N 3720986 R 1000 L 1000
#   done

 # echo "app = PPR, dataset = soc-LiveJournal1.txt from echo" >> graphchi_metrics.txt.statistics 
 #  echo "source=0, nsource=1, walkspersource=100000, nsteps=20 from echo" >> graphchi_metrics.txt.statistics 
 #  for(( times = 0; times < 10; times++))
 #  do
 #      echo "times = " $times " from echo"
 #      bin/example_apps/personalizedpagerank file '/home/wang/Documents/graph processing system/dataset/LiveJournal1/soc-LiveJournal1.txt' source 0 R 100000 niters 20
 #  done

  # echo "app = PPR, dataset = twitter_rv.net from echo" >> graphchi_metrics.txt.statistics 
  # echo "source=12, nsource=1, walkspersource=100000, nsteps=20 from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/personalizedpagerank file '/home/wang/Documents/graph processing system/dataset/Twitter/twitter_rv.net' nvertices 61578415 source 12 R 100000 niters 20
  # done

 #  echo "app = SimRank, dataset = soc-LiveJournal1.txt from echo" >> graphchi_metrics.txt.statistics 
 #  echo "R = 1600, L = 10,  a = 0, b = 1 from echo" >> graphchi_metrics.txt.statistics 
 #  for(( times = 0; times < 10; times++))
 #  do
 #      echo "times = " $times " from echo"
 #      bin/example_apps/simrank file '/home/wang/Documents/graph processing system/dataset/LiveJournal1/soc-LiveJournal1.txt' R 1600 L 10 a 0 b 1
 #  done

  # echo "app = SimRank, dataset = twitter_rv.net from echo" >> graphchi_metrics.txt.statistics 
  # echo "R = 1600, L = 10,  a = 12, b = 13 from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/simrank file '/home/wang/Documents/graph processing system/dataset/Twitter/twitter_rv.net' R 1600 L 10 a 12 b 13
  # done

  # echo "app = PPR, dataset = soc-LiveJournal1.txt from echo" >> graphchi_metrics.txt.statistics 
  # echo "source=0, nsource=1, walkspersource=1, nsteps=10000 (2928*7) from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/personalizedpagerank file '/home/wang/Documents/graph processing system/dataset/LiveJournal1/soc-LiveJournal1.txt'
  # done
  
  # echo "app = PPR, dataset = twitter_rv.net from echo" >> graphchi_metrics.txt.statistics 
  # echo "source=12, nsource=1, walkspersource=1, nsteps=10000 (2928*7) from echo" >> graphchi_metrics.txt.statistics 
  # for(( times = 0; times < 10; times++))
  # do
  #     echo "times = " $times " from echo"
  #     bin/example_apps/personalizedpagerank file '/home/wang/Documents/graph processing system/dataset/Twitter/twitter_rv.net'
  # done

